# Differentiating Points 3
```scala
do {
  accum = accum :+ produce()
} while(advanceCounters() != -1)
accum = accum :+ produce()
accum

@tailrec
def intersect0(accum: Seq[MultiRecord], start_ts: Long, itemList:Seq[Seq[Record]]): Seq[MultiRecord] = {
    if (start_ts == Long.MaxValue) return accum
    ...
    intersect0(accum :+ entry, next_start_ts, next_set)
}
```
Linear Control Flow for Functional vs advanceCounters()...
Theres no `-1` in our Algorithm!? 
Does an exception make more sense?? `throw CompletedException` 
